/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData weather_sunny = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData weather_fog = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData weather_rainy = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData weather_snowy = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData weather_cloudy = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData weather_windy_variant = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData weather_lightning = const IconData(0xe806, fontFamily: _kFontFam);
}
