name: sol_luna_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        #- asset: assets/fonts/OpenSans-Bold.ttf
        #- asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family:  WeatherIcons
      fonts:
        - asset: assets/fonts/WeatherIcons.ttf
    
